apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: rails
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - name: db
              mountPath: /var/lib/postgresql/data
              subPath: db
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
