---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: rails
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
  redis-config: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: rails
spec:
  containers:
    - name: redis
      image: redis:6.2
      command:
        - redis-server
        - "/redis-master/redis.conf"
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.5"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
          - key: redis-config
            path: redis.conf

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rails
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis