# NOTE: Bottlerocket AMI might not be available in all regions.
# Please check AWS official doc or below link for more details
# https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART.md#finding-an-ami
# A simple example of ClusterConfig object with Bottlerocket settings:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-cluster
  region: us-east-1

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 3
    instanceType: m6g.medium
    amifamily: Bottlerocket

  - name: spot
    amifamily: Bottlerocket
    instanceTypes:
      [
        "c3.large",
        "c4.large",
        "c5.large",
        "c5d.large",
        "c5n.large",
        "c5a.large",
      ]
    spot: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
